title: Simplifying Complexity
language: english
format: web
sidebar: docnav

# Link to home
url: https://friendly-kowalevski-8d7c63.netlify.com/
baseurl: .

destination: _site
port: 4000
highlighter: rouge
exclude:
  - mobi
  - pdf
format: web

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

collections:
  docs:
    output: true

sass:
    style: compressed

defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: default
      topnav: topnav
      sidebar: docnav
  -
    scope:
      path: ""
      type: docs
    values:
      layout: default
      topnav: topnav
      progress: true
      sidebar: docnav
  -
    scope:
      path: "images"
    values:
      image: true

plugins:
  - jekyll-redirect-from

########## UI text ###############

google_analytics:
disqus_shortname: idratherbewriting
google_analytics: UA-408430-5

uistring:
    tableofcontents: Table of Contents
    log_doc_issue: Log Doc Issue
    breadcrumb:
      home: Home
      documentation: Documentation
    expandall: Expand All
    collapseall: Collapse All
    title: Doc navigation # Displays as site title on top nav bar and on site metadata
    description: A guide for technical writers on simplifying complexity in documentation # Displays as site description meta
    github_edit_button_text: Edit on GitHub
    products: Products
    docindex_product: Product
    docindex_startpage: Starting page

####### Algolia configuration ###########
algolia:
  application_id: MXM0JWJNIW
  index_name: simplifyingcomplexity
